### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by fatuhoku** [codebox/moment-precise-range#11]
I'm a relative newbie at JavaScript and am unclear on how this package is supposed to be used.

**Comment by codebox** [comment]
You just need to include the [momentjs library](http://momentjs.com/) in your web page, followed by the readable-range.js file from this repo, then you should be able to run the code examples shown in the README

**Comment by fatuhoku** [comment]
@codebox okay, that's for browsers. How about on Node?

**Comment by codebox** [comment]
I have never used it with Node, I'm sure it won't be difficult to adapt though
