### ISSUE TITLE
missing information about minimum required moment.js version

### ISSUE THREAD

**Issue by melo0187** [codebox/moment-precise-range#19]
I was using moment.js 2.8.1 and including your plugin produced `Uncaught TypeError: m2.utcOffset is not a function`. This is because of the fact that utcOffset has been added to moment.js only in version 2.9.0.

So I was thinking that you might want to add this information as requirement to the README.md at least.
Just my 2 cents =)

**Comment by YacheLee** [comment]
I encounter the same issue too.

**Comment by codebox** [comment]
I have added the dependency on moment >= 2.9 into the package.json file - thanks for pointing this out.
