### ISSUE TITLE
ES6 import solution

### ISSUE THREAD

**Issue by chrisj-skinner** [codebox/moment-precise-range#26]
Hi,

In reference to issue: https://github.com/codebox/moment-precise-range/issues/25

When using ES6 a work around solution has been found: 

USE: 

var moment = require("moment");
var momentPreciseRangePlugin = require("moment-precise-range-plugin");`

and change line 2 in monent-precise-range.js to `var moment = require('moment');`

This plugin should in fact work with `import` when using ES6 but alas.
`import * as moment from 'moment';` WORKS!
`import [no-idea?] from 'moment-precise-range-plugin';` DOES NOT WORK as no ES6 imports in docs

I have put a pull request in for the above change in: https://github.com/codebox/moment-precise-range/blob/master/moment-precise-range.js

**Comment by gonzalobustos** [comment]
Hi @chrisj-skinner 

Were you finally able to import the package using ES6? If so, could you please tell me how.
Thanks!

**Comment by chrisj-skinner** [comment]
@gonzalobustos 
Yes, as mentioned above I used:
`const moment = require('moment');`
`const momentPreciseRangePlugin = require('moment-precise-range-plugin');`
