### ISSUE TITLE
Mark the old moment-precise-range NPM package as deprecated

### ISSUE THREAD

**Issue by ExplodingCabbage** [codebox/moment-precise-range#29]
A colleague of mine just added the (ancient, buggy) https://www.npmjs.com/package/moment-precise-range to a project of mine, not realising that he should've been using https://www.npmjs.com/package/moment-precise-range-plugin. To protect others from making the same mistake, could you mark the old package as deprecated using [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) and update its README to warn people not to use it?

**Comment by codebox** [comment]
I don't own that NPM repo unfortunately, you would have to contact the owner - see here: https://github.com/mtscout6/moment-precise-range
